### ISSUE TITLE
Few thoughts after reading the README

### ISSUE THREAD

**Issue by iRonin** [topofocus/active-orient#1]
First of all - it's great to see a gem supporting OrientDB!

How about naming it `rest-orient`? There is not that much ActiveRecord pattern there yet.
I would also suggest using `RESTOrient` or similar namespace instead of a more general `REST` namespace:

* `RESTOrient::Model`
* `RESTOrient.orientdb = RESTOrient::OrientDB.new`

Is there `#` missing here?

```
  r.get_document '21:1'
```

**Comment by topofocus** [comment]
Hi,
sorry for the delay – and thanks for the comment

The hole project is based on ActiveModel. You are right, the readme reflects an very early stage.
The target is to do as many things as smart as ActiveRecord. Therefore I like to keep it this way – unless somebody else claims to provide a better solution. 

The change of the Namespace REST is a good Idea.
Maybe to ActiveOrient?  
Then  Objects would be ActiveOrient::Base for the data-structure, 
 ActiveOrient::Model for the Database-Classes,
 ActiveOrient::OArray for Database-Collections  (don't know, if ActiveOrient::Array is possible)
 and ActiveOrient::REST for all low-level methods.


r.get_document accepts a rid and a link  (rid= '00:00', link= '#00:00') 
I am always confused, when to use what, so I delegated this to the program.


Summergreetings from Stuttgart
Hartmut
