### ISSUE TITLE
rspec failed.

### ISSUE THREAD

**Issue by tkaneda** [topofocus/active-orient#10]
I cloned repo and execute bundle install and rewrote config/connect.yml .
But I failed rspec.
Can I work well ?

**Comment by topofocus** [comment]
Good Morning,

I will work it out this evening.

Greetings

hartmut

Am 29.05.2016 um 15:13 schrieb Tadashi Kaneda:

**Comment by topofocus** [comment]
You are right. The spec's have not been updated correctly after changes made recently. 
I will post an update as soon as possible.  
Thanks for bringing this to my attention.

**Comment by tkaneda** [comment]
Thanks.
I will wait for your updates.

**Comment by topofocus** [comment]
Hi,
thanks for bringing the misbehaviour of the specs to my attention.

All specs are passing again.
Next we will update the project to support OrientDB 2.2

**Comment by topofocus** [comment]
As we are on the road to the next gem-release, many Specs are updated and now passing.
I will close this issue.
