### ISSUE TITLE
Issues with JRuby

### ISSUE THREAD

**Issue by abhi18av** [topofocus/active-orient#17]
Hii @topofocus 

Hey, I'm trying out this package with `jruby` - it works fine on the `mri`

I installed the `active-orient` and `active-model` gems via 
```sh
> jruby -S gem install active-orient
> jruby -S gem install activemodel -v 4.2.6
```
But when I try to do a simple `ActiveOrient::OrientDB.new database: 'GamesOfThrones'` in the `jirb` it gives the following error  `TypeError: no implicit conversion of nil into Hash`

Stack trace is as follows 

```sh
TypeError: no implicit conversion of nil into Hash
	from org/jruby/RubyHash.java:1708:in `merge!'
	from org/jruby/RubyHash.java:1744:in `merge'
	from /Users/eklavya/.jruby/lib/ruby/gems/shared/gems/active-orient-0.42/lib/rest.rb:50:in `initialize'
	from (irb):3:in `<eval>'
	from org/jruby/RubyKernel.java:995:in `eval'
	from org/jruby/RubyKernel.java:1296:in `loop'
	from org/jruby/RubyKernel.java:1115:in `catch'
	from org/jruby/RubyKernel.java:1115:in `catch'
	from /Users/eklavya/.jruby/bin//jirb:13:in `<main>'
```
Is there a solution to this ?

**Comment by topofocus** [comment]
Hi,


please use the bundler to install the package and use the github-resp. 
as source.

This is a sample gemfile:

  1 source "https://rubygems.org"
   2 #gemspec
   3 ## jruby support is experimental, not tested jet
   4 gem 'orientdb' , :git => 
'git://github.com/topofocus/orientdb-jruby.git' , :platforms => :jruby
   5
   6 gem 'active-orient' , :git => 
'git://github.com/topofocus/active-orient.git'
   7
   8
   9 group :development, :test do
  10         gem "awesome_print"
  11         gem "rspec"
  12         gem 'rspec-legacy_formatters'
  13         gem 'rspec-its'
  14         gem 'rspec-collection_matchers'
  15         gem 'rspec-context-private'
  16         gem 'guard-jruby-rspec', :platforms => :jruby, :git => 
'git://github.com/jkutner/guard-jruby-rspec.git'
  17         gem 'guard'#, :platforms => :ruby
  18         gem 'guard-rspec'
  19 ##      gem 'database_cleaner'
  20         gem 'rb-inotify'
  21         gem 'pry'
  22 end

Then I recommend to use

bin/active-orient-console

after modifying /config/connect.yml

As working sample for a project you might take a look at

https://github.com/topofocus/orientdb_time_graph

I want to use the quiet days until NewYear to continue the work on the 
project.
If you find bugs or miss features, let me know.

Greetings from Stuttgart

Hartmut
~

Am 16.12.2016 um 19:54 schrieb Abhinav Sharma:
> Hii @topofocus
>
> Hey, I'm trying out this package with `jruby` - it works fine on the `mri`
>
> I installed the `active-orient` and `active-model` gems via
> ```sh
>> jruby -S gem install active-orient
>> jruby -S gem install activemodel -v 4.2.6
> ```
> But when I try to do a simple `ActiveOrient::OrientDB.new database: 'GamesOfThrones'` in the `jirb` it gives the following error  `TypeError: no implicit conversion of nil into Hash`
>
> Is there a solution to this ?
>

**Comment by abhi18av** [comment]
Oh, that's great! Thanks, for working on this - it's appreciated :+1: 

I'm trying these out, will follow up with feedback for sure.
