### ISSUE TITLE
undefined method `default_server=' for ActiveOrient::OrientDB:Class

### ISSUE THREAD

**Issue by nishantkumar1292** [topofocus/active-orient#21]
I am using the **test_commands.rb** file in the examples folder as a standalone ruby script. I have the OrientDB server running locally. When I rub the script I get this error: **undefined method `default_server=' for ActiveOrient::OrientDB:Class (NoMethodError)**.

I thought of removing OrientDB from the line. Now I get this error:

       I, [2017-05-10T12:10:48.634338 #31412]  INFO -- OrientDB#Connect: Connected to database NewTest
       /home/user/.bundle/ruby/2.3.0/active-orient-fdae334715ca/lib/class_utils.rb:44:in `allocate_class_in_ruby': undefined method `const_defined?' for nil:NilClass (NoMethodError)
               from /home/user/.bundle/ruby/2.3.0/active-orient-fdae334715ca/lib/database_utils.rb:81:in `block in preallocate_classes'
               from /home/user/.bundle/ruby/2.3.0/active-orient-fdae334715ca/lib/database_utils.rb:80:in `each'
               from /home/user/.bundle/ruby/2.3.0/active-orient-fdae334715ca/lib/database_utils.rb:80:in `preallocate_classes'
               from /home/user/.bundle/ruby/2.3.0/active-orient-fdae334715ca/lib/rest/rest.rb:88:in `initialize'
               from test_commands.rb:8:in `new'
               from test_commands.rb:8:in `<main>'

Am I missing something or is this an issue?

**Comment by topofocus** [comment]
Hi,
please don't use this scripts anymore.

Use the rspec-examples instead.

I must confess, I did not update the examples a very long time. As I
recall, the streets example is not working, as the structure of the
referred side changed. However, the books example should work.

Next week, I will add an example which reads economic data from quandl and
puts it into the context of ActiveOrient.


Grüße

Hartmut Bischoff



2017-05-10 8:51 GMT+02:00 Nishant Kumar <notifications@github.com>:

**Comment by topofocus** [comment]
outdated.
