### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by StefanoMartin** [topofocus/active-orient#6]
I try some of the examples in your readme files and in your repository and I had some problems that I am not able to solve. To install your gem I used gem install active-orient
Here a short list.

- I use your commands to create these Vertexes and Edges:

```
require 'bundler/setup'
require 'active-orient'

ActiveOrient::OrientDB.default_server= { user: 'root', password: 'password' }
r = ActiveOrient::OrientDB.new database: 'First'

Vertex = r.create_vertex_class 'd1'
Edge = r.create_edge_class   'e1' # <--- Note, here I changed your Eedge in Edge

start =  Vertex.create  something: 'nice'
the_end   =  Vertex.create  something: 'not_nice'
the_edge = Edge.create_edge  attributes:  { transform_to: 'very bad' },
                 from: start,
                 to: the_end

print start.e1[0]

```
The vertex and edge are created, but when I want to print the result I receive:
```
I, [2016-03-16T10:13:44.185332 #1229]  INFO -- OrientDB#Connect: Connected to database First
D, [2016-03-16T10:13:51.499534 #1229] DEBUG -- ActiveOrient::OrientDB#NexusEdge: creating edge E1 from #13:0 to #13:1
testActiveOrient.rb:76:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
```

- I tried to use the Query command at the end of the readme file.
This is my code:
```
require 'bundler/setup'
require 'active-orient'
ActiveOrient::OrientDB.default_server= { user: 'root', password: 'password' }
r = ActiveOrient::OrientDB.new database: 'First'`
ach = ActiveOrient::Query.new

   ach.queries << 'create class Contracts ABSTRACT'
   ach.queries << 'create property Contracts.subcategory link'
   ach.queries << 'create property Contracts.details link'
   ach.queries << 'create class Stocks extends Contracts'
   ach.queries << 'create class Futures extends Contracts'
   result = ach.execute_queries transaction: false

print result
```

but the only result is the following:
```
I, [2016-03-16T10:22:40.414749 #1304]  INFO -- OrientDB#Connect: Connected to database First 
testActiveOrient.rb:78:in `<main>': uninitialized constant ActiveOrient::Query (NameError)
```

- In the file "street.rb" in the folder examples, I think that the German website has changed its css. For this reason I suggest to change this:
`strassen = doc.css('#strassen-in-deutschland_main a' )`
in this:
`strassen = doc.css("td[data-header='Straßenname: '] a")`

**Comment by topofocus** [comment]
Hi,
just back from easter-holiday's  in the beautiful landcape of the german-austrian border.
As you supplied a patch, which of the  topics above are still »open«?

**Comment by StefanoMartin** [comment]
Nice! I hope that you had a nice time on the Alps. :D 

All of them are solved, but the README needs to be updated. Tomorrow I will try to commit an updated readme.

**Comment by StefanoMartin** [comment]
I decide to answer here since the problem is more interesting that I was previously thinking.
The code on the README is not bad, but there is a small problem

```
Vertex = r.create_vertex_class 'd1'
Edge = r.create_edge_class   'e1' 
start =  Vertex.create  something: 'nice'
the_end   =  Vertex.create  something: 'not_nice'
the_edge = Edge.create_edge  attributes:  { transform_to: 'very bad' },
                 from: start,
                 to: the_end

print start.e1[0]
```
If I want to print start.e1[0] I don't obtain the edge that I wish. This happen since the edge has been created on the database but the variable start is still updated with the vertex without edge.
To solve the problem I need to retrieve the vertex and then I can print. 
In few word a good working code can be the following:

```
Vertex = r.create_vertex_class 'd1'
Edge = r.create_edge_class   'e1' 
start =  Vertex.create  something: 'nice'
the_end   =  Vertex.create  something: 'not_nice'
the_edge = Edge.create_edge  attributes:  { transform_to: 'very bad' },
                 from: start,
                 to: the_end
start = Vertex.get_documents where: {something: "nice"}
print start[0].e1[0]
```
Note I write start[0] instead of start since get_documents returns an array.

My second complain seems solved in the supplied patch.
